### ISSUE TITLE
Stopping `phx.server` doesn't stop bun

### ISSUE THREAD

**Issue by LostKobrakai** [crbelaus/elixir_bun#4]
`bun` needs to be stopped when the parent beam vm stops.

**Comment by crbelaus** [comment]
Thanks for this report.

I am able to reproduce this, but at the moment I am not sure how to fix it. Will keep investigating until I find a solution.

**Comment by LostKobrakai** [comment]
This documents the behaviour: https://hexdocs.pm/elixir/main/Port.html#module-zombie-operating-system-processes

The solution is to either make bun close when stdin is closed or put some script inbetween to do so.

**Comment by crbelaus** [comment]
In my own tests #5 fixes this issue. Could you check if it fixes it for you as well @LostKobrakai ?

**Comment by LostKobrakai** [comment]
Works here as well.

**Comment by crbelaus** [comment]
Great! Will submit a new version of the library today with the fix. In the meanwhile it is already available in master.
